---

# example code
:api_key: 09152cda1c3e8d0caa0de0898d08be41
:password: 8408e32325502c93c495b730138275a7
:store: pete-skate-shop.myshopify.com
:theme_id: 98481987
:ignore_files:
  # - settings_data.json
  # - logo.png
